### ISSUE TITLE
Remove .babelrc from the package

### ISSUE THREAD

**Issue by edoroshenko** [ForbesLindesay/redux-optimist#14]
I include the `redux-optimist` in a project that use babel 6. My build crashes, because in your `.babelrc` there is an option `optional`, that is not supported anymore.

**Comment by Macil** [comment]
See https://github.com/ForbesLindesay/redux-optimist/pull/12

> You should **not** be running babel in node_modules. If you do you will find that your build fails pretty frequently. You should only run babel on your own application code.

redux-optimist is published onto npm already compiled to ES5, so you shouldn't try to run it through babel again.
