### ISSUE TITLE
Is this package dead?

### ISSUE THREAD

**Issue by typeofweb** [ForbesLindesay/redux-optimist#26]

**Comment by ForbesLindesay** [comment]
No, this package is working fine.

**Comment by typeofweb** [comment]
Not mean to be rude, but that doesn't really answer my question. We're facing some hard choices in our project and we were considering using this package. However, lack of any activity whatsoever is very repulsant. I think you could agree it wouldn't be wise to depend on a package which is abandonded — in case any bugs or vulnerabilities appear.

There are 4 open issues and 6 pull requests, some of them for a few years now. Is this package under any development at all? Are the bugs being fixed? Is the FSA compliance going to be merged any time soon?

Thank you.

**Comment by albinotonnina** [comment]
Wonderful occasion to step-in and contribute to the (open-source) project, since you’re using it!

**Comment by typeofweb** [comment]
@albinotonnina I'm literally not using it yet. And I would love to contribute, however at the moment there are 6 open PRs ignored for years so chances are mine would be ignored just as well :) Cheer 👍
